import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider";
//styles
import localFont from 'next/font/local'

import "@/styles/globals.css";
//components
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

//fonts
const IRANSans = localFont({
  src: [
    {
      path: "../../public/fonts/iransans/IRANSansWeb_Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansWeb.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansWeb_Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/IRANSansWeb_Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-iran-sans",
})

const IRANSansFaNum = localFont({
  src: [
    {
      path: "../../public/fonts/iransans/fa/IRANSansWeb_Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/fa/IRANSansWeb.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/fa/IRANSansWeb_Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/iransans/fa/IRANSansWeb_Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-iran-sans-fa-num",
})


//SEO & meta-data
export const metadata: Metadata = {
  title: "Lindo | e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${IRANSans.className} antialiased`}>
        {/* <ThemeProvider 
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
        </ThemeProvider> */}
            <Header />
            {children}
            <Footer />
      </body>
    </html>
  );
}
